In [1]:
import os 
import sys 
import glob 
import re
import nltk 
import logging 

import numpy as np 
import pandas as pd 

os.chdir(r'C:\Users\ADMIN\Documents\Nam_3\CS419\project')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from collections import Counter
from source.utils.textPreprocessing import TextPreprocessing
from source.utils.inverted_index import InvertedIndex

In [2]:
docs_fp = r'C:\Users\ADMIN\Documents\Nam_3\CS419\project\data\documents.csv'
queries_fp = r'C:\Users\ADMIN\Documents\Nam_3\CS419\project\data\queries.csv'

docs_df = pd.read_csv(docs_fp)
queries_df = pd.read_csv(queries_fp)

In [4]:
docs_processing = TextPreprocessing() 
processed_docs = docs_processing.process_dataframe(dataframe=docs_df) 
vocab = docs_processing.get_vocab() 
processed_docs

,id,content,tokens
0,1,experimental investigation of the aerodynamics...,"[experimental, investigation, aerodynamics, wi..."
1,10,the theory of the impact tube at low pressure ...,"[theory, impact, tube, low, pressure, theoreti..."
2,100,vibration isolation of aircraft power plants ....,"[vibration, isolation, aircraft, power, plant,..."
3,1000,free flight measurements of the static and dyn...,"[free, flight, measurement, static, dynamic, s..."
4,1001,wind tunnel investigation of the static and dy...,"[wind, tunnel, investigation, static, dynamic,..."
...,...,...,...
1395,995,,[]
1396,996,extension of boundary layer separation criteri...,"[extension, boundary, layer, separation, crite..."
1397,997,experimental and theoretical studies of axisym...,"[experimental, theoretical, study, axisymmetri..."
1398,998,"equations, tables and charts for compressible ...","[equation, table, chart, compressible, flow, r..."
1399,999,static aerodynamic characteristics of short bl...,"[static, aerodynamic, characteristic, short, b..."

In [5]:
def _build_term_docs(vocab, docs_df): 
    term_docs = [] 
    docs_size = docs_df.shape[0]
    for i in range(len(vocab)): 
        r = [0] * docs_size 
        term_docs.append(r) 

    for i in range(docs_size): 
        for w in docs_df['tokens'].iloc[i]: 
            for j in range(len(vocab)): 
                if vocab[j] == w : 
                    term_docs[j][i] += 1
                    break
                
    return term_docs

term_docs = _build_term_docs(vocab=vocab, docs_df=processed_docs)

In [6]:
type(term_docs)

list

In [7]:
sample = queries_df.iloc[0]
sample

id                                                         1
content     what similarity laws must be obeyed when cons...
Name: 0, dtype: object

In [8]:
sample_tokens = docs_processing._text_preprocessing(sample['content']) 
sample_tokens

['similarity',
 'law',
 'must',
 'obeyed',
 'constructing',
 'aeroelastic',
 'model',
 'heated',
 'high',
 'speed',
 'aircraft']

In [9]:
def boolean_query(query:str, term_docs_dict:list, vocab:list, operator='OR') -> list:
    query_tokens = docs_processing._text_preprocessing(query)  
    print(f"="*10)
    print(f"Query tokens: ")
    print(query_tokens)
    print(f"="*10)

    word2idx = {word: i for i, word in enumerate(vocab)}
    print(f"="*10)
    print(f"word2idx: ")
    print(word2idx)
    print(f"="*10)

    target_indices = [word2idx[t] for t in query_tokens if t in word2idx]
    print(f"="*10)
    print(f"target_indices : ")
    print(target_indices)
    print(f"="*10)

    if not target_indices:
        return []
    
    matrix = np.array(term_docs_dict)
    res_vector = matrix[target_indices[0]]

    for idx in target_indices[1:]:
        if operator == "AND":
            res_vector = res_vector & matrix[idx]
        else: 
            res_vector = res_vector | matrix[idx]

    matching_doc_indices = np.where(res_vector > 0)[0]
    return matching_doc_indices.tolist()

query = sample['content']
result = boolean_query(query=query, term_docs_dict=term_docs, vocab=vocab, operator="OR")

==========
Query tokens:
['similarity', 'law', 'must', 'obeyed', 'constructing', 'aeroelastic', 'model', 'heated', 'high', 'speed', 'aircraft']
==========
==========
word2idx:

In [10]:
result

[2,
 3,
 4,
 5,
 6,
 10,
 13,
 15,
 16,
 19,
 24,
 25,
 31,
 35,
 40,
 43,
 46,
 47,
 49,
 50,
 59,
 64,
 70,
 71,
 72,
 73,
 75,
 81,
 82,
 84,
 87,
 90,
 92,
 95,
 98,
 99,
 100,
 102,
 103,
 105,
 107,
 110,
 113,
 115,
 118,
 125,
 126,
 128,
 129,
 130,
 137,
 140,
 141,
 151,
 157,
 158,
 161,
 162,
 165,
 170,
 172,
 173,
 174,
 176,
 177,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 191,
 199,
 202,
 203,
 206,
 208,
 214,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 226,
 227,
 228,
 230,
 235,
 237,
 238,
 239,
 242,
 244,
 245,
 246,
 251,
 252,
 253,
 256,
 257,
 258,
 264,
 267,
 268,
 273,
 275,
 277,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 291,
 292,
 294,
 296,
 299,
 300,
 302,
 303,
 306,
 309,
 311,
 313,
 315,
 318,
 319,
 322,
 323,
 324,
 326,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 336,
 339,
 340,
 341,
 345,
 347,
 348,
 349,
 350,
 351,
 352,
 356,
 358,
 359,
 360,
 362,
 363,
 366,
 371,
 373,
 374,
 375,
 376,
 377,
 378,
 380,
 381,
 383,
 386,
 387,
 389,
 390,
 391,
 392,
 397,
 403,
 404,
 407,
 415,
 416,
 417,
 418,
 421,
 422,
 424,
 429,
 434,
 436,
 438,
 441,
 445,
 446,
 448,
 449,
 451,
 453,
 460,
 462,
 464,
 466,
 469,
 472,
 474,
 475,
 477,
 478,
 480,
 482,
 484,
 486,
 487,
 489,
 491,
 494,
 495,
 498,
 500,
 501,
 505,
 507,
 509,
 510,
 512,
 513,
 515,
 516,
 517,
 518,
 519,
 520,
 522,
 523,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 536,
 538,
 539,
 541,
 542,
 545,
 547,
 549,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 560,
 561,
 562,
 563,
 566,
 568,
 570,
 571,
 572,
 574,
 580,
 581,
 582,
 583,
 584,
 586,
 590,
 593,
 595,
 601,
 602,
 605,
 606,
 607,
 609,
 610,
 612,
 615,
 616,
 617,
 619,
 620,
 624,
 625,
 627,
 629,
 630,
 631,
 634,
 637,
 640,
 641,
 642,
 645,
 646,
 648,
 654,
 655,
 656,
 657,
 659,
 660,
 662,
 666,
 668,
 671,
 674,
 678,
 679,
 682,
 683,
 684,
 688,
 689,
 690,
 691,
 695,
 697,
 702,
 705,
 706,
 710,
 712,
 713,
 721,
 724,
 725,
 729,
 731,
 735,
 737,
 740,
 742,
 743,
 746,
 747,
 750,
 752,
 753,
 757,
 758,
 759,
 761,
 767,
 769,
 770,
 772,
 774,
 775,
 777,
 778,
 780,
 781,
 782,
 783,
 785,
 787,
 790,
 793,
 794,
 796,
 797,
 804,
 806,
 807,
 808,
 810,
 812,
 817,
 819,
 825,
 830,
 835,
 836,
 838,
 839,
 840,
 842,
 844,
 846,
 849,
 855,
 856,
 857,
 859,
 861,
 864,
 867,
 868,
 869,
 871,
 874,
 875,
 878,
 879,
 880,
 886,
 891,
 892,
 893,
 894,
 897,
 900,
 904,
 905,
 912,
 916,
 917,
 919,
 921,
 922,
 923,
 925,
 926,
 927,
 928,
 930,
 931,
 932,
 934,
 939,
 940,
 943,
 944,
 947,
 948,
 949,
 957,
 958,
 959,
 960,
 961,
 963,
 964,
 974,
 977,
 979,
 980,
 983,
 984,
 985,
 986,
 988,
 989,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1002,
 1005,
 1007,
 1018,
 1019,
 1020,
 1021,
 1023,
 1024,
 1026,
 1027,
 1029,
 1030,
 1031,
 1034,
 1035,
 1036,
 1037,
 1038,
 1040,
 1041,
 1044,
 1047,
 1049,
 1051,
 1052,
 1053,
 1056,
 1057,
 1062,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1076,
 1077,
 1078,
 1080,
 1081,
 1082,
 1083,
 1084,
 1087,
 1089,
 1091,
 1092,
 1093,
 1095,
 1096,
 1097,
 1100,
 1111,
 1113,
 1119,
 1120,
 1123,
 1125,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1139,
 1142,
 1149,
 1150,
 1152,
 1156,
 1158,
 1160,
 1166,
 1167,
 1168,
 1169,
 1170,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1179,
 1180,
 1181,
 1184,
 1185,
 1188,
 1191,
 1192,
 1193,
 1195,
 1196,
 1197,
 1198,
 1199,
 1201,
 1206,
 1212,
 1217,
 1219,
 1221,
 1223,
 1234,
 1243,
 1244,
 1246,
 1248,
 1251,
 1257,
 1258,
 1261,
 1262,
 1263,
 1265,
 1266,
 1268,
 1270,
 1271,
 1272,
 1274,
 1276,
 1278,
 1283,
 1285,
 1289,
 1294,
 1295,
 1299,
 1300,
 1303,
 1304,
 1306,
 1308,
 1309,
 1310,
 1311,
 1312,
 1314,
 1316,
 1317,
 1318,
 1320,
 1333,
 1336,
 1339,
 1340,
 1341,
 1342,
 1343,
 1345,
 1347,
 1356,
 1357,
 1358,
 1359,
 1363,
 1367,
 1371,
 1374,
 1377,
 1380,
 1381,
 1385,
 1386,
 1390,
 1391,
 1394,
 1398,
 1399]

In [11]:
processed_docs.iloc[result]

,id,content,tokens
2,100,vibration isolation of aircraft power plants ....,"[vibration, isolation, aircraft, power, plant,..."
3,1000,free flight measurements of the static and dyn...,"[free, flight, measurement, static, dynamic, s..."
4,1001,wind tunnel investigation of the static and dy...,"[wind, tunnel, investigation, static, dynamic,..."
5,1002,preliminary investigations of spiked bodies at...,"[preliminary, investigation, spiked, body, hyp..."
6,1003,free flight measurements of the static and dyn...,"[free, flight, measurement, static, dynamic, r..."
...,...,...,...
1390,990,a rapid approximate method for determining vel...,"[rapid, approximate, method, determining, velo..."
1391,991,wing flow study of pressure drag reduction at ...,"[wing, flow, study, pressure, drag, reduction,..."
1394,994,investigation of a retrocket exhausting from t...,"[investigation, retrocket, exhausting, nose, b..."
1398,998,"equations, tables and charts for compressible ...","[equation, table, chart, compressible, flow, r..."
1399,999,static aerodynamic characteristics of short bl...,"[static, aerodynamic, characteristic, short, b..."

## **Inverted Index**

In [14]:
inverted_indx_builder = InvertedIndex(processed_docs_df=processed_docs, vocab=vocab) 
inverted_indx_builder._build() 

inverted_index = inverted_indx_builder.get_inverted_index()

In [26]:
inverted_index['rapid']['df']

32

In [21]:
exp_list = []

In [23]:
a = list(inverted_index['comparative']['postings'].keys())

In [24]:
b = list(inverted_index['retrocket']['postings'].keys())

In [25]:
exp_list.append(np.logical_or(a, b)) 
exp_list

[array([ True,  True,  True,  True,  True,  True])]